name: Test Crash PyPy + skia-pathops

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PyPy 3.7
        uses: actions/setup-python@v2
        with:
          python-version: pypy-3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-deps

      - name: Run test
        run: |
          python -u pathops-randomshapes.py
